version: '3'

services:
  postgres:
    image: postgres 
    ports:
        - "5432:5432"
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_NAME: postgres
  web:
    build:
        context: .
        dockerfile: Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DEBUG=1
