# Generated by Django 2.2.5 on 2020-10-19 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_swapped', models.BooleanField(default=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.Shift')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='vehicles',
            field=models.ManyToManyField(through='shifts.VehicleShift', to='vehicles.Vehicle'),
        ),
    ]
