# Generated by Django 2.2.5 on 2020-10-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicleshift',
            unique_together={('vehicle', 'shift')},
        ),
    ]
